### ISSUE TITLE
Pod install using 'use_frameworks!' option

### ISSUE THREAD

**Issue by dbulaienko** [gontovnik/DGRunkeeperSwitch#11]
Hi! I'm trying to integrate your project with obj-c code, so i'm using option 'use_frameworks!' for pod install.
When i import this module, none of classes are visible. That is because classes are not public. 
Could you please provide public access level for main classes? 

P.S. i know that there is already objective-c implementation, but i want to be sure that i'd have your last updates just in time. 
Thanks

**Comment by gontovnik** [comment]
Hi Dmitry! Please try to install pods again. I just pushed version 1.1.1 to github and cocoapods. Please let me know whether it works for you now.

**Comment by dbulaienko** [comment]
wow, that was realy fast! thanks! :) 
Yep, now the classes are visible, but unfortunately, the initializers and properties, that you defined under mark 'public vars' are still not visible..So still can't use it.
 That's because it's defined as internal by default and  'use_frameworks!' required public access level for that. 
Thanks in advance

**Comment by gontovnik** [comment]
Try it again, pushed changes with public vars/funcs and tagged it as 1.1.1

**Comment by dbulaienko** [comment]
awesome, working as expected :) :+1:  Many thanks!

**Comment by gontovnik** [comment]
You are welcome :)
